name: Sync Fork Upstream

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@latest
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          owner: Mydong
          repo: ChatGPT-Next-Web
          branch: main
