on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  # - cron: '0 0 * * *' # 每天同步一次
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          owner: ChatGPTNextWeb
          base: main
          head: main
